DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS courses CASCADE;
DROP TABLE IF EXISTS tutors CASCADE;
DROP TABLE IF EXISTS programs CASCADE;



CREATE TABLE users (
  id SERIAL PRIMARY KEY NOT NULL,
  uid VARCHAR(255) NOT NULL,
  email VARCHAR(255) NOT NULL,
  program VARCHAR(255),
  is_active boolean DEFAULT true,
  is_tutor boolean DEFAULT false
);

CREATE TABLE courses (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
);


CREATE TABLE tutors (
  id SERIAL PRIMARY KEY NOT NULL,

  course_list text[]
);

CREATE TABLE programs (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL
)

