INSERT INTO courseItems (name, title, subject, year, description)
VALUES
('MATH 211', 'Linear Methods I', 'MATH', 1, 'An introduction to systems of linear equations, vectors in Euclidean space and matrix algebra. Additional topics include linear transformations, determinants, complex numbers, eigenvalues, and applications.'),
('MATH 275', 'Calculus for Engineers and Scientists', 'MATH', 1, 'An extensive treatment of differential and integral calculus in a single variable, with an emphasis on applications. Differentiation: derivative laws, the mean value theorem, optimization, curve sketching and other applications. Integral calculus: the fundamental theorem of calculus, techniques of integration, improper integrals, and areas of planar regions. Infinite series: power series, Taylor’s theorem and Taylor series.'),
('MATH 277', 'Multivariable Calculus for Engineers and Scientists', 'MATH', 1, 'An introduction to calculus of several real variables: curves and parametrizations, partial differentiation, the chain rule, implicit functions; integration in two and three variables and applications; optimization and Lagrange multipliers.'),
('ENGG 201', 'Behavior of Liquids, Gases, and Solids', 'ENGG', 1, 'An introduction to the behaviour of fluids and solids; phase transformations, the phase rule and phase diagrams. Ideal and real gases; equations of state and their engineering applications; simple kinetic theory; transport properties of fluids. Liquid state; vapor pressure; shear behaviour; flow of fluids in pipelines. Solids; crystalline and non-crystalline structure; non-equilibrium solid phases; electrical and thermal conductivity; dislocations; stress and strain; creep; fracture.'),
('ENGG 202', 'Engineering Statics', 'ENGG', 1, 'Force vectors; equilibrium of a particle in two and three dimensions; force system resultants; equilibrium of a rigid body in two and three dimensions; internal forces in trusses; frames, machines and beams; bending moment and shear force diagrams; friction; centre of gravity; centroids of areas; composite bodies.'),
('ENGG 225', 'Fundamentals of Electrical Circuits and Machines', 'ENGG', 1, 'Current, voltage and power; Kirchoff’s current and voltage laws; capacitors; electricity and magnetism fundamentals applied to circuit elements and machines; inductors; topics in electrical circuits and systems; instrumentation; circuit design, DC and AC circuit analysis methods; DC and AC machines; first order circuits and transient analysis.'),
('PHYS 259', 'Electricity and Magnetism', 'PHYS', 1, 'Electric and magnetic fields related to charges and current through Maxwell’s equations. Energy stored in fields, potential energy, and voltage. Conductors, insulators, and dielectrics. Resistance, capacitance, and inductance with applications to RC/RL circuits.'),
('CHEM 209', 'General Chemistry for Engineers', 'CHEM', 1, 'Basic chemical concepts. Atomic and molecular structure. Chemical bonding. Chemical kinetics and equilibria. Acid-base and solubility equilibria. Oxidation-reduction phenomena and electrochemistry. The chemistry of water. The chemistry of energy sources. Basic environmental issues.'),
('MATH 375', 'Differential Equations for Engineers and Scientists', 'MATH', 2, 'Definition, existence and uniqueness of solutions; first order and higher order equations and applications; Homogeneous systems; Laplace transform; partial differential equations of mathematical physics.'),
('ENGG 311', 'Engineering Thermodynamics', 'ENGG', 2, 'Energy, thermodynamic systems, properties and state, temperature and the zeroth law, equilibrium, properties of the pure substance, equations of state. Work, reversibility, heat, first law, specific heats, enthalpy, ideal gas, flow systems. Entropy and the second law, Carnot cycle, thermodynamic temperature scale, process efficiencies, cycles, calculation of entropy change, exergy analysis.'),
('ENME 341', 'Fundamentals of Fluid Mechanics', 'ENME', 2, 'Basic principles of mechanics of fluids. Fluid statics: forces on surfaces, buoyancy, stability. Continuity, energy and momentum equations applied to control-volume analysis. Dimensional analysis and physical similarity. Introduction to external flows and flow through pipes. Applications to a variety of problems in mechanical engineering.'),
('ENEL 327', 'Signals and Transforms', 'ENEL', 2, 'Continuous-time systems. Impulse response and convolution. Fourier series and Fourier transform. Basics of discrete time signals. Sampling theory. Discrete convolution. Difference equations and the Z-transform. Discrete-time Fourier representations.'),
('ENEL 343', 'Circuits II', 'ENEL', 2, 'Laplace transform methods for circuit analysis. Transfer functions and series and parallel resonance. Basic filter theory and Bode diagrams. Natural, step, and transient responses of RL, RC, and RLC circuits. Two-port circuits. Two-port circuit parameters: admittance, impedance and hybrid parameters.'),
('ENER 460', 'Dynamics for Energy Engineering II', 'ENER', 3, 'Planar kinematics and kinetics of rigid bodies; work, energy, impulse and momentum of rigid bodies; kinematics, statics, and dynamics of planar mechanisms; design of cams, gears, and gear trains.');